config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    get 'card', on: :member
    get 'logout', on: :member
  end
  resources :items do
    resources :buys, only: [:new, :create] do
      collection do
        get 'done', to: 'buys#done'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # 編集画面でのカテゴリー表示
    member do
      get 'get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # バリデーション後のカテゴリー取得
  get 'get_category_children', to: 'items#get_category_children'
  get 'get_category_grandchildren', to: 'items#get_category_grandchildren'

  resources :cards, only: [:index, :new, :create, :destroy]

end

app/views/share/_add-card.html.haml
.card-content_main
  .card-content_main_text
    = "支払い方法"
  .card-content_main_top
    = "クレジットカード一覧"
  .card-content_main_box
    = link_to new_card_path do
      .card-content_main_box_btn
        .card-content_main_box_btn_icon
          .far.fa-credit-card
        .card-content_main_box_btn_text
          = "クレジットカードを追加する"
  .card-content_main_info
    = "支払い方法について"
    .fa.fa-chevron-right

app/views/share/_download-banner.html.haml
.download-banner
  .inner
    .inner_title だれでもかんたん、人生を変えるフリマアプリ
    .inner_text 今すぐ無料ダウンロード！
    .inner_icon
      .inner_icon_app
        = image_tag "app-store-badge.svg", width: "170px"
      .inner_icon_google
        = image_tag "google-play-badge.svg", width: "190px"

app/views/share/_exhibit-btn.html.haml
- if user_signed_in?
  = link_to new_item_path do
    .exhibit-btn
      .exhibit-btn_text
        = "出品する"
      .exhibit-btn_icon
        = image_tag "icon/icon_camera.png", width: "100%"
- else
  = link_to  new_user_session_path do
    .exhibit-btn
      .exhibit-btn_text
        = "出品する"
      .exhibit-btn_icon
        = image_tag "icon/icon_camera.png", width: "100%"

app/views/share/_exist-card.html.haml
.card-content_main
  - if @card.present?
    .card-content_main_text
      = '支払い方法'
    = form_with url: card_path(@card.id), method: :delete, local: true, id: 'charge-form' do |f|
      .card-content_main_top
        = 'クレジットカード一覧'
      .card-content_main_index
        .card-content_main_index_left
          -# カードブランドのアイコンを表示
          = image_tag "credit-cards/#{@card_src}", height: '30px', alt: @card_brand, id: "card_image"
          .card-content_main_index_left_pay-num
            = "************" + @card_information.last4
          .card-content_main_index_left_pay-num
            - exp_month = @card_information.exp_month.to_s
            - exp_year = @card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %input{type: "hidden", name: "card_id", value: ""}
        .card-content_main_index_right
          = f.submit "削除する", {class: "card-content_main_index_right_list-remove"}
          - if flash[:notice]
            .alert.alert-success
              = flash[:notice]
          - if flash[:alert]
            .alert.alert-failed
              = flash[:alert]
  - else
    = render "share/add-card"

app/views/share/_footer.html.haml
.footer
  %ul.footer-contents
    %li.content
      %h2.content_head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#"
        %li
          = link_to "プライバシーポリシー", "#"
        %li
          = link_to "FURIMA利用規約", "#"
        %li
          = link_to "ポイントに関する特約", "#"
    %li.content
      %h2.content_head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", "#"
        %li
          = link_to "ブランド一覧", "#"
    %li.content
      %h2.content_head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", "#"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          = link_to "お知らせ", "#"
  .footer-logo
    = image_tag 'logo/logo-white.png', width: '170px'
  .footer-copylight
    = "©️FURIMA"

app/views/share/_header.html.haml
.header-area
  .header-area_top
    .header-area_top_icon
      = link_to root_path do
        = image_tag 'logo/logo.png', height: '100%'
    .header-area_top_search
      .header-area_top_search_form
        = 'キーワードから探す'
      .header-area_top_search_btn
        .header-area_top_search_btn_icon
          = image_tag 'icon/icon-search 1.png', height: '100%'
  .header-area_bottom
    .header-area_bottom_select
      .header-area_bottom_select_category
        = link_to '' do
          = 'カテゴリー'
      .header-area_bottom_select_brand
        = link_to '' do
          = 'ブランド'
    .header-area_bottom_user
      .header-area_bottom_user_login
        - if user_signed_in?
          = link_to 'ログアウト', destroy_user_session_path, method: :delete
        - else
          = link_to 'ログイン', user_session_path
      .header-area_bottom_user_new
        - if user_signed_in?
          = link_to 'マイページ', user_path(current_user)
        - else
          = link_to '新規会員登録', new_user_registration_path

app/views/share/_side.html.haml
%nav.side-bar
  %ul.side-bar_list
    %li.side-bar_list-item-link
      = link_to "マイページ", user_path
      %i.fa.fa-chevron-right
    = link_to  new_item_path do
      %li.side-bar_list-item-link
        = "出品する"
        %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "下書き一覧"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "出品した商品 - 出品中"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "出品した商品 - 取引中"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "出品した商品 - 売却済み"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = " 購入した商品 - 取引中"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "購入した商品 - 過去の取引"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "ニュース一覧"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "ガイド"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "お問い合わせ"
      %i.fa.fa-chevron-right

  %h1.side-nav-head 設定
  %ul.side-bar_list
    %li.side-bar_list-item
      = "プロフィール"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "発送元・お届け先住所変更"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "支払い方法"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "メール/パスワード"
      %i.fa.fa-chevron-right
    %li.side-bar_list-item
      = "本人情報"
      %i.fa.fa-chevron-right
    = link_to card_user_path do
      %li.side-bar_list-item-link
        = "クレジットカード登録"
        %i.fa.fa-chevron-right
    = link_to logout_user_path do
      %li.side-bar_list-item-link
        = "ログアウト"
        %i.fa.fa-chevron-right

app/views/share/_top-icon.html.haml
.top-icon
  .top-icon_image
    = link_to root_path do
      = image_tag 'logo/logo.png', width: '100%'