config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    get 'card', on: :member
    get 'logout', on: :member
  end
  resources :items do
    resources :buys, only: [:new, :create] do
      collection do
        get 'done', to: 'buys#done'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # 編集画面でのカテゴリー表示
    member do
      get 'get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # バリデーション後のカテゴリー取得
  get 'get_category_children', to: 'items#get_category_children'
  get 'get_category_grandchildren', to: 'items#get_category_grandchildren'

  resources :cards, only: [:index, :new, :create, :destroy]

end

app/controllers/buys_controller.rb
class BuysController < ApplicationController

  before_action :set_item
  before_action :set_card

  require 'payjp'

  def new
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def create
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    charge = Payjp::Charge.create(
    amount: @item.price,
    customer: @card.customer_id,
    currency: 'jpy'
    )
    if @item.save
      @item.update(state: 2, buyer: current_user.id)
      redirect_to action: 'done'
    else
      flash[:alert] = '購入に失敗しました。'
      redirect_to action: "new"
    end
  end

  def done
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @card_information = customer.cards.retrieve(@card.card_id)
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/done.html.haml
= render 'share/top-icon'

.buy-content
  .buy-content_message
    .buy-content_message_top
      = '発送をお待ちください'
    .buy-content_message_bottom
      = '出品者からの発送通知をお待ちください'
  .buy-content_title
    = '購入が完了しました'
  .buy-content_item
    .buy-content_item_image
      = image_tag @item.item_images.first.image.url, class: 'buy-content_item_image_main'
    .buy-content_item_detail
      .buy-content_item_detail_name
        = @item.name
      .buy-content_item_detail_price
        = "¥#{@item.price.to_s(:delimited)} (税込) 送料込み"
  .buy-content_info
    .buy-content_info_price
      .buy-content_info_price_total
        .buy-content_info_price_total_text
          = '支払い金額'
        .buy-content_info_price_total_number
          = "¥#{@item.price.to_s(:delimited)}"
    .buy-content_info_pay
      .buy-content_info_pay_top
        .buy-content_info_pay_top_text
          = '支払い方法'
      .buy-content_info_pay_bottom
        .buy-content_info_pay_bottom_card
          = 'クレジットカード'
        .buy-content_info_pay_bottom_number
          = "************" + @card_information.last4
        .buy-content_info_pay_bottom_deadline
          = '有効期限 '
          - exp_month = @card_information.exp_month.to_s
          - exp_year = @card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
    .buy-content_info_address
      .buy-content_info_address_top
        .buy-content_info_address_top_text
          = '配送先'
      .buy-content_info_address_bottom
        .buy-content_info_address_bottom_post
          = current_user.address.postal_code
        .buy-content_info_address_bottom_address
          = current_user.address.prefecture.name
          = current_user.address.city
          = current_user.address.street
          = current_user.address.building
        .buy-content_info_address_bottom_user
          = current_user.lastname
          = current_user.firstname
    .buy-content_info_purchase
      = link_to root_path do
        .buy-content_info_purchase_btn
          = 'トップページに戻る'
.buy-bottom

app/views/buys/new.html.haml
= render 'share/top-icon'

.buy-content
  .buy-content_title
    = '購入内容の確認'
  .buy-content_item
    .buy-content_item_image
      = image_tag @item.item_images.first.image.url, class: 'buy-content_item_image_main'
    .buy-content_item_detail
      .buy-content_item_detail_name
        = @item.name
      .buy-content_item_detail_price
        = "¥#{@item.price.to_s(:delimited)} (税込) 送料込み"
  .buy-content_info
    .buy-content_info_price
      .buy-content_info_price_total
        .buy-content_info_price_total_text
          = '支払い金額'
        .buy-content_info_price_total_number
          = "¥#{@item.price.to_s(:delimited)}"
      .buy-content_info_price_point
        .buy-content_info_price_point_square
        .buy-content_info_price_point_text
          = 'ポイントを使用(所持ポイント:P0)'
    .buy-content_info_pay
      - if @card.present?
        .buy-content_info_pay_top
          .buy-content_info_pay_top_text
            = '支払い方法'
          .buy-content_info_pay_top_change
            = link_to '変更する', new_card_path
        .buy-content_info_pay_bottom
          .buy-content_info_pay_bottom_card
            = 'クレジットカード'
          .buy-content_info_pay_bottom_number
            = "************" + @card_information.last4
          .buy-content_info_pay_bottom_deadline
            = '有効期限 '
            - exp_month = @card_information.exp_month.to_s
            - exp_year = @card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
      - else
        .buy-content_info_pay_top
          .buy-content_info_pay_top_text
            = '支払い方法'
        .buy-content_info_pay_register
          = link_to '+ 登録してください', new_card_path
    .buy-content_info_address
      .buy-content_info_address_top
        .buy-content_info_address_top_text
          = '配送先'
        .buy-content_info_address_top_change
          = link_to '変更する', '#'
      .buy-content_info_address_bottom
        .buy-content_info_address_bottom_post
          = current_user.address.postal_code
        .buy-content_info_address_bottom_address
          = current_user.address.prefecture.name
          = current_user.address.city
          = current_user.address.street
          = current_user.address.building
        .buy-content_info_address_bottom_user
          = current_user.lastname
          = current_user.firstname
    - if @card.present?
      .buy-content_info_purchase
        = link_to item_buys_path(@item.id), method: :post do
          .buy-content_info_purchase_btn
            = '購入する'
    - else
      = ''
.buy-bottom