config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    get 'card', on: :member
    get 'logout', on: :member
  end
  resources :items do
    resources :buys, only: [:new, :create] do
      collection do
        get 'done', to: 'buys#done'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # 編集画面でのカテゴリー表示
    member do
      get 'get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # バリデーション後のカテゴリー取得
  get 'get_category_children', to: 'items#get_category_children'
  get 'get_category_grandchildren', to: 'items#get_category_grandchildren'

  resources :cards, only: [:index, :new, :create, :destroy]

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  validates :name, :detail, :price, :state, :condition, :prefecture, :shipping_cost, :shipping_date, :shipping_method, :item_images, presence: true
  validates :name, length: { maximum: 40 }
  validates :detail, length: { maximum: 1000 }
  validates :price, numericality: { greater_than_or_equal_to: 300 }
  validates :price, numericality: { less_than_or_equal_to: 9999999 }
  validates :state, numericality: { greater_than_or_equal_to: 0 }
  validates :state, numericality: { less_than_or_equal_to: 3 }
  validate :item_images_number

  def  item_images_number
    errors.add(:item_images, "は10枚までです") if item_images.size > 10
  end

  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_cost
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :shipping_date
  
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  belongs_to :user
  belongs_to :category
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_parents

  def index
    @items = Item.includes(:item_images).order('created_at DESC').limit(3)
    @item_images = ItemImage.all
  end

  def new
    @item = Item.new
    @item.item_images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      @item.update(state: 1)
      redirect_to root_path
    else
      @item.item_images.new
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @category = @item.category
  end

  def edit
    @item = Item.find(params[:id])
    if @item.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update

    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      if @item.category_id == 0
        @item = Item.find(params[:id])
        flash.now[:alert] = 'カテゴリーを入力してください'
        render :edit
      else
        render :edit
      end
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  private

  def item_params
    params.require(:item).permit(:name, :detail, :price, :brand, :condition_id, :shipping_cost_id, :shipping_method_id, :prefecture_id, :shipping_date_id, :item_id, :category_id, item_images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id )
  end

  def set_parents
    # データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent = Category.where(ancestry: nil)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
= render 'share/top-icon'

.exhibit-form
  .notifications
    - flash.each do |key, value|
      = content_tag(:div, value, class: key)
  = form_with model: @item, local: true do |f|
    - if @item.errors.any?
      .exhibit-form_errors
        %h2= "#{@item.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @item.errors.full_messages.each do |message|
            %li= message
            
    .image-container
      .image-container_box
        .form-title
          %span.box-form-explanaion
            商品画像
          %span.indispensable
            必須
        %p.image-container_box_message
          最大10枚までアップロードできます
        .image-container_box_alart-10
          ※ 1枚目は必須です
      -# .image-container_unit-man
      -#   .image-container_unit-man_preview
      #image-box
        #previews
          - if @item.persisted?
            - @item.item_images.each_with_index do |image, i|
              = image_tag image.image.url, data: { index: i }, width: "118", height: '150'
        = f.fields_for :item_images do |image|
          .js-file_group{"data-index" => "#{image.index}"}
            = image.file_field :image, class: 'js-file'
            %br/
            %span.js-remove 削除
          - if @item.persisted?
            = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
        - if @item.persisted?
          - if @item.item_images.count < 10
            .js-file_group{"data-index" => "#{@item.item_images.count}"}
              = file_field_tag :image, name: "item[item_images_attributes][#{@item.item_images.count}][image]", class: 'js-file'
              .js-remove 削除

    .explain-container
      .explain-container_name-box
        .form-title
          %span.box-form-explanaion
            商品名
          %span.indispensable
            必須
        = f.text_field :name, placeholder: "40文字まで", maxlength:"40", class: 'exhibit-form-field'
      .explain-container_text-box
        .form-title
          %span.box-form-explanaion
            商品の説明
          %span.indispensable
            必須
        = f.text_area :detail, maxlength:"1000", class: 'exhibit-form-detail', placeholder: '商品の説明 (最大 1000文字) (色、素材、重さ、定価、注意点など) 例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。'
        .explain-container_text-box_info
          0/1000

    .detail-container
      %p.container-title 商品の詳細
      .box_form
        = f.label :category_id , class: 'wrapper__label category-wrapper-label', id: "wrapper__label--category" do
          .form-title
            %span.box-form-explanaion
              カテゴリー
            %span.indispensable
              必須
          .form-select-category
            .form-select-category__option
              = f.collection_select(:category_id, Category.where(ancestry: nil), :id, :name, {prompt: "---", selected: @item.category.parent.parent_id}, {id: "parent_category"})
            .form-select-category#children_wrapper
              .form-select-category__option
                = f.collection_select(:category_id, @item.category.parent.parent.children, :id, :name, {prompt: "---", selected: @item.category.parent_id}, {id: "child_category"})
            .form-select-category#grandchildren_wrapper
              .form-select-category__option
                = f.collection_select(:category_id, @item.category.parent.children, :id, :name, {prompt: "---", selected: @item.category.id}, {id: "grand_child_category"})
      .box_form
        .form-title
          %span.box-form-explanaion
            ブランド
          %span.indispensable_optional
            任意
        = f.text_field :brand, placeholder: "例) シャネル", maxlength:"40", class: 'exhibit-form-field'
      .box_form
        .form-title
          %span.box-form-explanaion
            商品の状態
          %span.indispensable
            必須
        = f.collection_select :condition_id, Condition.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}

    .shipping-container
      %p.container-title 配送について
      .box_form
        .form-title
          %span.box-form-explanaion
            配送料の負担
          %span.indispensable
            必須
        = f.collection_select :shipping_cost_id, ShippingCost.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
      .box_form  
        .form-title
          %span.box-form-explanaion
            配送の方法
          %span.indispensable
            必須
        = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
      .box_form
        .form-title
          %span.box-form-explanaion
            発送元の地域
          %span.indispensable
            必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
      .box_form
        .form-title
          %span.box-form-explanaion
            発送までの日数
          %span.indispensable
            必須
        = f.collection_select :shipping_date_id, ShippingDate.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}

    .price-container
      %p.container-title 価格 (¥300~9,999,999)
      .calculation-box
        .selling-price-line
          .selling-form-title
            .form-title
              %span.box-form-explanaion
                販売価格
              %span.indispensable
                必須
          = f.number_field :price, placeholder: "0", min: 0, max: 9999999, class: 'exhibit-form_price' do
            %span.mark
              ¥
            .exhibit-form_right
        .commission-line
          .commission-line_left
            販売手数料 (10%)
          .commission-line_right
            ー
        .profit-line
          .profit-line_left
            販売利益
          .profit-line_right
            ー
      .price-box-btn
        = f.submit class: "price-box-btn_exhibit-btn" do
          nil
        = link_to "もどる", :back, class: "price-box-btn_back-btn"





-# = render 'share/top-icon'
-# .exhibit-form
-#   = form_with model: @item, local: true do |f|
-#     - if @item.errors.any?
-#       .exhibit-form_errors
-#         %h2= "#{@item.errors.full_messages.count}件のエラーが発生しました。"
-#         %ul
-#           - @item.errors.full_messages.each do |message|
-#             %li= message
-#     .image-container
-#       .image-container_box
-#         .form-title
-#           %span.box-form-explanaion
-#             商品画像
-#           %span.indispensable
-#             必須
-#         %p.image-container_box_message
-#           最大10枚までアップロードできます
-#         .image-container_box_alart-10
-#           ※ 1枚目は必須です
-#       .image-container_unit-man
-#         - if @item.persisted?
-#           - @item.item_images.each_with_index do |image, i|
-#             - unless image.image.url == nil
-#               = f.hidden_field :id, value: image.object_id
-#               = f.check_box :_destroy, data: { index: i }, class: "check-box-#{i}"
-#               .item-image-container__unit
-#                 .item-image-container__unit__image
-#                   = image_tag image.image.url, data: { index: i }
-#                   .image-option__list--tag 削除
                  
-#         %div{class: "item-image-container__unit preview-#{@item.item_images.length - 1}"}
-#           .image-container__unit--guide
-#             .have-image
-#               %i.fas.fa-camera
-#             = f.fields_for :item_images do |i|
-#               = i.file_field :image, class: 'img-man', id:"image-label-0",type: 'file'
              
-#     .explain-container
-#       .explain-container_name-box
-#         .form-title
-#           %span.box-form-explanaion
-#             商品名
-#           %span.indispensable
-#             必須
-#         = f.text_field :name, placeholder: "40文字まで", maxlength:"40", class: 'exhibit-form-field'
-#       .explain-container_text-box
-#         .form-title
-#           %span.box-form-explanaion
-#             商品の説明
-#           %span.indispensable
-#             必須
-#         = f.text_area :detail, maxlength:"1000", class: 'exhibit-form-detail', placeholder: '商品の説明 (最大 1000文字) (色、素材、重さ、定価、注意点など) 例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。'
-#         .explain-container_text-box_info
-#           0/1000
-# ​
-#     .detail-container
-#       %p.container-title 商品の詳細
-#       .box_form
-#         .form-title
-#           %span.box-form-explanaion
-#             カテゴリー
-#           %span.indispensable
-#             必須
-#         .form-select-category
-#           .form-select-category__option
-#             = f.collection_select :category_id, @category_parent, :id, :name, {prompt: "選択してください"}, class: 'form-select__option-box', id: 'parent_category'
-#       .box_form
-#         .form-title
-#           %span.box-form-explanaion
-#             ブランド
-#           %span.indispensable_optional
-#             任意
-#         = f.text_field :brand, placeholder: "例) シャネル", maxlength:"40", class: 'exhibit-form-field'
-#       .box_form
-#         .form-title
-#           %span.box-form-explanaion
-#             商品の状態
-#           %span.indispensable
-#             必須
-#         = f.collection_select :condition_id, Condition.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
-# ​
-#     .shipping-container
-#       %p.container-title 配送について
-#       .box_form
-#         .form-title
-#           %span.box-form-explanaion
-#             配送料の負担
-#           %span.indispensable
-#             必須
-#         = f.collection_select :shipping_cost_id, ShippingCost.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
-#       .box_form  
-#         .form-title
-#           %span.box-form-explanaion
-#             配送の方法
-#           %span.indispensable
-#             必須
-#         = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
-#       .box_form
-#         .form-title
-#           %span.box-form-explanaion
-#             発送元の地域
-#           %span.indispensable
-#             必須
-#         = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
-#       .box_form
-#         .form-title
-#           %span.box-form-explanaion
-#             発送までの日数
-#           %span.indispensable
-#             必須
-#         = f.collection_select :shipping_date_id, ShippingDate.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
-# ​
-#     .price-container
-#       %p.container-title 価格 (¥300~9,999,999)
-#       .calculation-box
-#         .selling-price-line
-#           .selling-form-title
-#             .form-title
-#               %span.box-form-explanaion
-#                 販売価格
-#               %span.indispensable
-#                 必須
-#           = f.number_field :price, placeholder: "0", min: 0, max: 9999999, class: 'exhibit-form_price' do
-#             %span.mark
-#               ¥
-#             .exhibit-form_right
-#         .commission-line
-#           .commission-line_left
-#             販売手数料 (10%)
-#           .commission-line_right
-#             ー
-#         .profit-line
-#           .profit-line_left
-#             販売利益
-#           .profit-line_right
-#             ー
-#       .price-box-btn
-#         = f.submit class: "price-box-btn_exhibit-btn" do
-#           nil
-#         = link_to "もどる", :back, class: "price-box-btn_back-btn"

app/views/items/index.html.haml
=render 'share/header'
  
.main
  .main__top-banner
    .main__top-banner__container
      %h2.main__top-banner__container__title-man
        %br
        人生を変えるフリマアプリ
      %p.main__top-banner__container__text-man
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .main__top-banner__container__inner_icon
        .main__top-banner__container__inner_icon__app
          = image_tag "app-store-badge.svg", width: "170px"
        .main__top-banner__container__inner_icon__google
          = image_tag "google-play-badge.svg", width: "190px"

  .main__introduction
    .introduction__reason-for-chose
      FURIMAが選ばれる3つの理由
    .introduction__reason-lists
      %ul.lists
        %li.lists__list
          .lists__list--picture
            %p.number 1
            = image_tag 'pict/pict-reason-01.jpg', width: "100%"
          .lists__list--text
            %span 3分
            ですぐに出品
          .lists__list--discription
            スマホで入力するだけで簡単に出品できる！
        %li.lists__list
          .lists__list--picture
            %p.number 2
            = image_tag 'pict/pict-reason-02.jpg', width: "100%"
          .lists__list--text
            %span シンプル 
            で使いやすい
          .lists__list--discription
            めんどくさい入力は必要なく、検索も購入もスムーズ！
        %li.lists__list.lists__list-last
          .lists__list--picture
            %p.number 3
            = image_tag 'pict/pict-reason-03.jpg', width: "100%"
          .lists__list--text
            手数料 
            %span 業界最安
          .lists__list--discription
            最大3%でお得に出品&購入！

  .main__middle-banner
    .main__middle-banner__container
      .main__middle-banner__container__title-man
        会員数日本一位  
      .main__middle-banner__container__text-man
        FURIMAは、フリマアプリで最も人気。 
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .main__middle-banner__container__inner_icon
        .main__middle-banner__container__inner_icon__app
          = image_tag "app-store-badge.svg", width: "170px"
        .main__middle-banner__container__inner_icon__google
          = image_tag "google-play-badge.svg", width: "190px"

  .main__feature
    .main__feature__title
      FURIMAの特徴
    .main__feature__feature-lists 
      .list
        .list__picture
          = image_tag 'icon/icon-01.png', class: "feature-picture"
        .list__text
          簡単に売り買いできる
        .list__discription
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .list
        .list__picture
          = image_tag 'icon/icon-03.png', class: "feature-picture"
        .list__text
          売上金は即日振込みに対応
        .list__discription
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .list
        .list__picture
          = image_tag 'icon/icon-04.png', class: "feature-picture"
        .list__text
          様々な支払いに対応
        .list__discription
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    
  .main__pic-up
    .main__pic-up__category
      .main__pic-up__category__title
        ピックアップカテゴリー 
      .main__pic-up__category__sub-title
        新規投稿商品
      .main__pic-up__content
        - @items.each do |item|
          .item
            .item__image
              -item.item_images.each_with_index do |image, index|
                - if index == 0
                  = link_to item_path(item.id) do
                    = image_tag image.image.url
                - else
            .item__body
              .item__body__name
                = item.name
              .item__body__middle
                .item__body__middle__price
                  = item.price
                .item__body__middle__favorite
              .item__body__fee
                (税込)
            - if item.state == 2
              .item__sold-out__area
              .item__sold-out__text
                = 'SOLD'
    .main__pic-up__brand
      .main__pic-up__brand__title
        ピックアップブランド
      .main__pic-up__brand__sub-title
        アーカイバ
      .main__pic-up__content
        - @items.each do |item|
          .item
            .item__image
              -item.item_images.each_with_index do |image, index|
                - if index == 0
                  = link_to item_path(item.id) do
                    = image_tag image.image.url
                - else
            .item__body
              .item__body__name
                = item.name
              .item__body__middle
                .item__body__middle__price
                  = item.price
                .item__body__middle__favorite
              .item__body__fee
                (税込)
            - if item.state == 2
              .item__sold-out__area
              .item__sold-out__text
                = 'SOLD'

  = render 'share/download-banner'

  =render 'share/footer'

  =render 'share/exhibit-btn'

app/views/items/new.html.haml
= render 'share/top-icon'
.exhibit-form
  = form_with model: @item, local: true do |f|
    - if @item.errors.any?
      .exhibit-form_errors
        %h2= "#{@item.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @item.errors.full_messages.each do |message|
            %li= message
    .image-container
      .image-container_box
        .form-title
          %span.box-form-explanaion
            商品画像
          %span.indispensable
            必須
        %p.image-container_box_message
          最大10枚までアップロードできます
        .image-container_box_alart-10
          ※ 1枚目は必須です
      .image-container_unit-man
        .item-image-container__unit.preview-0
          = f.fields_for :item_images do |i|
            .image-container__unit--guide
              = i.file_field :image, class: 'img-man', id:"image-label-0",type: 'file'
              .have-image
                %i.fas.fa-camera

    .explain-container
      .explain-container_name-box
        .form-title
          %span.box-form-explanaion
            商品名
          %span.indispensable
            必須
        = f.text_field :name, placeholder: "40文字まで", maxlength:"40", class: 'exhibit-form-field'
      .explain-container_text-box
        .form-title
          %span.box-form-explanaion
            商品の説明
          %span.indispensable
            必須
        = f.text_area :detail, maxlength:"1000", class: 'exhibit-form-detail', placeholder: '商品の説明 (最大 1000文字) (色、素材、重さ、定価、注意点など) 例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。'
        .explain-container_text-box_info
          0/1000

    .detail-container
      %p.container-title 商品の詳細
      .box_form
        .form-title
          %span.box-form-explanaion
            カテゴリー
          %span.indispensable
            必須
        .form-select-category
          .form-select-category__option
            = f.collection_select :category_id, @category_parent, :id, :name, {include_blank: "選択してください"}, class: 'form-select__option-box', id: 'parent_category'
      .box_form
        .form-title
          %span.box-form-explanaion
            ブランド
          %span.indispensable_optional
            任意
        = f.text_field :brand, placeholder: "例) シャネル", maxlength:"40", class: 'exhibit-form-field'
      .box_form
        .form-title
          %span.box-form-explanaion
            商品の状態
          %span.indispensable
            必須
        = f.collection_select :condition_id, Condition.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}

    .shipping-container
      %p.container-title 配送について
      .box_form
        .form-title
          %span.box-form-explanaion
            配送料の負担
          %span.indispensable
            必須
        = f.collection_select :shipping_cost_id, ShippingCost.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
      .box_form  
        .form-title
          %span.box-form-explanaion
            配送の方法
          %span.indispensable
            必須
        = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
      .box_form
        .form-title
          %span.box-form-explanaion
            発送元の地域
          %span.indispensable
            必須
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}
      .box_form
        .form-title
          %span.box-form-explanaion
            発送までの日数
          %span.indispensable
            必須
        = f.collection_select :shipping_date_id, ShippingDate.all, :id, :name, {prompt:"選択してください"}, {class: 'exhibit-form-field'}

    .price-container
      %p.container-title 価格 (¥300~9,999,999)
      .calculation-box
        .selling-price-line
          .selling-form-title
            .form-title
              %span.box-form-explanaion
                販売価格
              %span.indispensable
                必須
          = f.number_field :price, placeholder: "0", min: 0, max: 9999999, class: 'exhibit-form_price' do
            %span.mark
              ¥
            .exhibit-form_right
        .commission-line
          .commission-line_left
            販売手数料 (10%)
          .commission-line_right
            ー
        .profit-line
          .profit-line_left
            販売利益
          .profit-line_right
            ー
      .price-box-btn
        = f.submit class: "price-box-btn_exhibit-btn" do
          nil
        = link_to "もどる", :back, class: "price-box-btn_back-btn"

app/views/items/show.html.haml
=render "share/header"
.show-item
  .show-item_nav
    = 'FRIMA >'
    = @category.parent.parent.name
    = ' > '
    = @category.parent.name
    = ' > '
    = @category.name
  .show-item_main
    .show-item_main_name
      = @item.name
    .show-item_main_img
      .show-item_main_img_main
        = image_tag @item.item_images.first.image.url class: 'item-image'
      .show-item_main_img_sub
        - @item.item_images.each do |i|
          .show-item_main_img_sub_content
            = image_tag i.image.url, class: 'item-image'
    .show-item_main_price
      .show-item_main_price_value
        = "¥#{@item.price.to_s(:delimited)}"
      .show-item_main_price_cost
        - if @item.shipping_cost.id == 1
          = '(税込)送料込み'
        - elsif @item.shipping_cost.id == 2
          = '(税込)着払い'
        - else
          = ''
    .show-item_main_message
      = @item.detail
    .show-item_main_detail
      .show-item_main_detail_box
        .show-item_main_detail_box_header
          %table
            %tr
              %th 出品者
            %tr
              %th カテゴリー
            %tr
              %th ブランド
            %tr
              %th 商品の状態
            %tr
              %th 配送料の負担
            %tr
              %th 配送の方法
            %tr
              %th 発送元の地域
            %tr
              %th 発送日の目安
        .show-item_main_detail_box_data
          %table
            %tr
              %td
                = @item.user.nickname
            %tr
              %td
                = @category.parent.parent.name
                = ' > '
                = @category.parent.name
                = ' > '
                = @category.name
            %tr
              %td
                - if @item.brand.present?
                  = @item.brand
                - else
                  = 'なし'
            %tr
              %td
                = @item.condition.name
            %tr
              %td 
                = @item.shipping_cost.name
            %tr
              %td 
                = @item.shipping_method.name
            %tr
              %td 
                = @item.prefecture.name
            %tr
              %td 
                = @item.shipping_date.name
      - if @item.state == 1 && user_signed_in? && current_user.id != @item.user.id
        .show-item_main_buy
          = link_to new_item_buy_path(@item.id) do
            .show-item_main_buy_text
              = '購入画面に進む'
      - elsif @item.state == 2
        .show-item_main_sold-out
          = '売り切れました'
      - elsif @item.state == 1 && user_signed_in? && current_user.id == @item.user.id
        .show-item_main_edit
          = link_to edit_item_path do
            .show-item_main_edit_text
              = '編集する'
        .show-item_main_destroy
          = link_to item_path, method: :delete do
            .how-item_main_destroy_text
              = '削除する'
      - else
        .show-item_main_buy
          = link_to new_user_session_path do
            .show-item_main_buy_text
              = '購入画面に進む'
  .show-item_comment
    .show-item_comment_form
      %label{for: "msg"}
      %textarea#msg{name: "user_message"}
    .show-item_comment_notice
      = '相手のことを考え丁寧なコメントを心がけましょう。'
      = '不快な言葉遣いなどは利用制限や退会処分となることがあります。'
    .show-item_comment_btn
      = link_to 'コメントする', "#", class: "cta-btn"

=render "share/download-banner"
=render "share/footer"