config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    get 'card', on: :member
    get 'logout', on: :member
  end
  resources :items do
    resources :buys, only: [:new, :create] do
      collection do
        get 'done', to: 'buys#done'
      end
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    # 編集画面でのカテゴリー表示
    member do
      get 'get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', to: 'items#get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  # バリデーション後のカテゴリー取得
  get 'get_category_children', to: 'items#get_category_children'
  get 'get_category_grandchildren', to: 'items#get_category_grandchildren'

  resources :cards, only: [:index, :new, :create, :destroy]

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :user_id, :customer_id, :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card

  def index #CardのデータをPayjpに送って情報を取り出す
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)

      # 登録しているカード会社のブランドアイコンを表示する
      @card_brand = @card_information.brand
      case @card_brand
        when "Visa"
          @card_src = "visa.svg"
        when "JCB"
          @card_src = "jcb.svg"
        when "MasterCard"
          @card_src = "mastercard.svg"
        when "American Express"
          @card_src = "american-express.svg"
        when "Diners Club"
          @card_src = "diners-club.svg"
        when "Discover"
          @card_src = "discover.svg"
      end
    end
  end

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "index" if card.exists?
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "create"
      end
    end
  end

  def destroy #PayjpとCardのデータベースを削除
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    if @card.destroy #削除に成功した時にポップアップを表示
      redirect_to action: "index", notice: "削除しました"
    else #削除に失敗した時にアラートを表示
      redirect_to action: "index", alert: "削除できませんでした"
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/index.html.haml
= render 'share/top-icon'

.card-content
  = render 'share/exist-card'

app/views/cards/new.html.haml
= render 'share/header'

.card-content
  .card-content_main
    .card-content_main_text
      = 'クレジットカード情報入力'
    .card-content_main_box
      = form_with url: cards_path, method: :post, html: { name: "inputForm" } do |f|
        .card-content_main_box_top
          .label
            = f.label :number, 'カード番号'
          %span.indispensable
            = '必須'
        .card-content_main_box_bottom
          = f.text_field :number, placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .card-content_main_box_top
          .label
            = f.label :exp_month, '有効期限'
          %span.indispensable
            = '必須'
        .card-content_main_box_bottom
          .select_half
            = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , id: 'exp_month'
            = '月'
          .select_half
            = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , id: 'exp_year'
            = '年'
        .card-content_main_box_top
          .label
            = f.label :cvc, 'セキュリティーコード'
          %span.indispensable
            = '必須'
        .card-content_main_box_bottom
          = f.text_field :cvc, placeholder: "カード背面4桁もしくは3桁の番号" ,maxlength: "4", id: "cvc"
        #card_token
          = submit_tag "追加する", id: "token_submit"